---
- hosts: localhost
  become: true
  tasks:
    - name: Ensure Docker Compose file is present
      copy:
        src: ./docker-compose.yml
        dest: /vagrant/docker-compose.yml
        owner: vagrant
        mode: '0644'

    - name: Run Docker Compose
      shell: |
        cd /vagrant
        docker compose up -d
      args:
        chdir: /vagrant
