---
- hosts: all
  become: true
  tasks:
    - name: Copy docker-compose.yml to the instance
      copy:
        src: ./docker-compose.yml
        dest: /home/cal/docker-compose.yml
        owner: cal
        mode: '0644'

    - name: Run Docker Compose
      shell: |
        cd /home/cal
        docker compose up -d
