---
# - name: Check if app-net network exists
#   command: docker network inspect app-net
#   register: network_check
#   ignore_errors: yes

- name: Create Docker network app-net
  docker_network:
    name: app-net2
    state: present
  # when: network_check.failed

- name: Create Docker volume for MongoDB
  docker_volume:
    name: app-mongo-data
    state: present

- name: Run MongoDB Container
  docker_container:
    name: app-ip-mongo
    image: mongo:4.4.3
    state: started
    restart_policy: always
    published_ports:
      - "27017:27017"
    volumes:
      - app-mongo-data:/data/db
    networks:
      - name: app-net2
