---
- name: Create Docker volume for MongoDB
  docker_volume:
    name: app-mongo-data
    state: present

- name: Create Docker network
  docker_network:
    name: app-net
    state: present

- name: Run MongoDB Container
  docker_container:
    name: app-ip-mongo
    image: mongo:4.4.3
    state: started
    restart_policy: always
    published_ports:
      - "27017:27017"
    volumes:
      - app-mongo-data:/data/db
    networks:
      - name: app-net
