version: "3.9"
services:
  calnexus-yolo-client:
    image: unitybi/yolo:client-v1.0.0
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: calnexus-yolo-client
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - calnexus-yolo-backend
    networks:
      - app-net

networks:
  app-net:
    external: true
