version: "3.9"
services:
  calnexus-yolo-backend:
    image: unitybi/yolo:backend-v1.0.0
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: calnexus-yolo-backend
    stdin_open: true
    tty: true
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - app-ip-mongo
    networks:
      - app-net
    environment:
      - MONGODB_URI=mongodb://app-ip-mongo:27017/yolomy

networks:
  app-net:
    external: true
