apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    app: mongo
spec:
  ports:
  - port: 27017
  selector:
    app: mongo
  clusterIP: None # Ensures it is only accessible within the cluster, and necessary for StatefulSets
